### ISSUE TITLE
Add ERB support so ERB can be used inside the yml files

### ISSUE THREAD

**Issue by essame** [baraabourghli/constantizer#8]
To make something like this possible,

``` yaml
default_currency: <%= CURRENCIES.first %>
currencies:
  - USD
  - EUR
```
